### ISSUE TITLE
Magisk Manager - "The zip is not a Magisk Module!!"

### ISSUE THREAD

**Issue by ryanguy426** [Magisk-Modules-Repo/Nexus6_LED_Enabler#2]
The module refuses to install from Magisk Manager, it claims it's not a module. 

Magisk Version: v7
Magisk Manager version: 2.0
Android version: 7.0 Factory Image

**Comment by stangri** [comment]
No ZIPs are provided, not sure where did you get one. Install it thru Magisk Manager/Downloads.

**Comment by ryanguy426** [comment]
I did. It claims it's not a module after download...

**Comment by stangri** [comment]
Just removed/re-added the module and I can't reproduce your error. Provide better steps for reproducing the bug.
