### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by testbug87** [Magisk-Modules-Repo/Nexus6_LED_Enabler#6]
Hi,

it seems that your module is not compatible with the recent magisk. The module is not listed, manual installation aborts.

> update-binary: line 146: /data/magisk/sepolicy-inject: not found
> update-binary: source: line 169: config.sh: not found
> - Copying zip to temp directory
> - Installing Nexus6LEDEnabler.zip
> Archive:  /data/user/0/com.topjohnwu.magisk/cache/install.zip
>   inflating: config.sh
> Failed!
> ! Installation failed

**Comment by testbug87** [comment]
@stangri Do you plan to update this module?

**Comment by stangri** [comment]
No, feel free to fork and update.
